const themes = [
  "Goth",
  "Vaporwave",
  "Steampunk",
  "90s",
  "80s",
  "70s",
  "Kitch",
  "Lumberjack",
  "Twin Peaks",
  "Greasy Strangler",
  "Seinfeld",
  "60s Diner",
  "18th-Century",
  "Retro Futurism",
  "Dadaism",
  "American Dad",
  "The Simpsons",
  "Star Wars",
];

const cuisines = [
  "Korean Food",
  "Indian Food",
  "Soul Food",
  "Mexican Food",
  "Jamaican Food",
  "Brazilian Food",
  "Cajun Food",
  "Italian Food",
  "German Food",
  "Swedish Food",
  "Thai Food",
  "Exotic Meats",
  "Spicy Food",
  "Vegan Cuisine",
  "Seafood",
  "Charcuterie",
  "Barbecue",
  "a Mystery Pitch-in",
  "Baked Goods",
  "Desserts",
  "All Kinds of Chocolate",
];

const indulgences = [
  "Celebrity-branded Alcohols",
  "White Wine",
  "Red Wine",
  "Cigars",
  "Bourbon",
  "Mezcal",
  "Bring-your-own Cocktails",
];

const activities = [
  "Watch Plinkett Reviews",
  "Watch Good Eats",
  "Play Jackbox Games",
  "Play Board Games",
  "Play 90s Video Games",
  "Watch B-Horror Movies",
  "Watch a Classic Comedy",
  "Watch Technology Connections",
];
