const themes = [
  "Goth",
  "Vaporwave",
  "Steampunk",
  "90s",
  "80s",
  "70s",
  "Kitch",
  "Lumberjack",
  "Twin Peaks",
  "Greasy Strangler",
  "Seinfeld",
  "60s Diner",
  "18th-Century",
  "Retro Futurism",
  "Dadaism",
  "American Dad",
  "The Simpsons",
  "Star Wars",
];

const cuisines = [
  "Korean Food",
  "Indian Food",
  "Soul Food",
  "Mexican Food",
  "Jamaican Food",
  "Brazilian Food",
  "Cajun Food",
  "Italian Food",
  "German Food",
  "Swedish Food",
  "Thai Food",
  "Exotic Meats",
  "Spicy Food",
  "Vegan Cuisine",
  "Seafood",
  "Charcuterie",
  "Barbecue",
  "a Mystery Pitch-in",
  "Baked Goods",
  "Desserts",
  "All Kinds of Chocolate",
  "Specialty Pizza",
  "a Sundae Bar",
  "Submarine Sandwiches",
];

const indulgences = [
  "Celebrity-branded Alcohols",
  "White Wine",
  "Red Wine",
  "Cigars",
  "Bourbon",
  "Mezcal",
  "Bring-your-own Cocktails",
  "Mojitos",
  "Mules",
  "Martinis",
  "Margaritas",
  "CBD Gummies",
  "Dessert Coffees",
  "Hookah",
  "Exotic Candy",
  "Hard Cider",
  "Craft Beer",
];

const activities = [
  "Watch Plinkett Reviews",
  "Watch Good Eats",
  "Play Jackbox Games",
  "Play Board Games",
  "Play 90s Video Games",
  "Watch B-Horror Movies",
  "Watch a Classic Comedy",
  "Watch Technology Connections",
  "Play Classic Card Games",
  "Play Minecraft",
  "Listen to Alternative Rap",
  "Bake Cookies",
  "Share YouTube Videos to Watch",
  "Watch King of the Hill",
];

const formats = [
  "How about a <b>{0}</b>-themed night where we have <b>{1}</b> and <b>{2}</b> and we <b>{3}</b>?",
  "What about a <b>{0}</b>-themed party where we have <b>{1}</b> as well as <b>{2}</b> and we <b>{3}</b>?",
  "How about this: a <b>{0}</b>-themed evening. We'll have <b>{1}</b> and <b>{2}</b> and also we'll <b>{3}</b>.",
];
